apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client-deployment
  labels:
    app: web-client
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
      version: v1
  template:
    metadata:
      labels:
        app: web-client
        version: v1
    spec:
      containers:
        - name: web-client
          image: mrtousif/web-client
          imagePullPolicy: 'IfNotPresent'
          resources:
            requests:
              cpu: '100m'
              memory: '100Mi'
            limits:
              cpu: '500m'
              memory: '500Mi'
          ports:
            - containerPort: 3000
          env:
            - name: KEYCLOAK_ID
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-host
            - name: KEYCLOAK_SECRET
              value: '6379'
            - name: KEYCLOAK_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-host
---
apiVersion: v1
kind: Service
metadata:
  name: web-client
spec:
  #   type: NodePort
  selector:
    app: web-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      #   nodePort: 30001
      name: http
