apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-service-deployment
  labels:
    app: tickets-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-service
      version: v1
  template:
    metadata:
      labels:
        app: tickets-service
        version: v1
    spec:
      containers:
        - name: tickets-service
          image: mrtousif/tickets-service:main
          imagePullPolicy: 'IfNotPresent'
          resources:
            requests:
              cpu: '100m'
              memory: '100Mi'
            limits:
              cpu: '500m'
              memory: '500Mi'
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-host
            - name: REDIS_PORT
              value: '6379'
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_URI
              value: mongodb://mongoadmin:secret@$(MONGO_HOST):27017
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-service
spec:
  #   type: NodePort
  selector:
    app: tickets-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      #   nodePort: 30001
      name: http
