apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  namespace: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
        - name: redpanda-console
          image: redpandadata/console:v2.3.8
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              value: 'my-cluster-kafka-brokers.kafka.svc.cluster.local'
