resources:
  - echo-server.yaml
  - ingress.yaml
  - ./order-service/order-service.yaml
  - ./tickets-service/tickets-service.yaml
  - ./payment-service/payment-service.yaml
  - ./web-client/web-client.yaml

# configMapGenerator
# generate a ConfigMap named envs-<some-hash> where each key/value pair in the
# env file appears as a data entry (separated by \n).
configMapGenerator:
  - name: shared-envs
    envs:
      - shared.env
