apiVersion: v1
# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: postgres-config
  labels:
    app: postgres
data:
  postgres-host: postgres-service:5432
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
data:
  initdb.sql: |
    CREATE USER service_one_user WITH PASSWORD 'password123';
    CREATE DATABASE service_one_db;
    GRANT ALL PRIVILEGES ON DATABASE service_one_db TO service_one_user;

    CREATE USER service_two_user WITH PASSWORD 'password123';
    CREATE DATABASE service_two_db;
    GRANT ALL PRIVILEGES ON DATABASE service_two_db TO service_two_user;

    CREATE USER service_three_user WITH PASSWORD 'password123';
    CREATE DATABASE service_three_db;
    GRANT ALL PRIVILEGES ON DATABASE service_three_db TO service_three_user;
